### ISSUE TITLE
No profile matching suffix "xccdf_org.ssgproject.content_profile_opencis-master"

### ISSUE THREAD

**Issue by akilada** [openshift/compliance-operator#292]
Hi,

I'm trying to run CIS master profile on OCP 4.3.24 cluster. 

The following is my ComplianceSuite config

```
apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: opencis-master
spec:
  autoApplyRemediations: false
  schedule: "0 6 * * *"
  scans:
    - name: masters-scan
      scanType: Node
      profile: xccdf_org.ssgproject.content_profile_opencis-master
      content: ssg-ocp4-ds.xml
      contentImage: quay.io/complianceascode/ocp4:latest
      nodeSelector:
        node-role.kubernetes.io/master: ""
```
However, the scan exists with the following error.

```
Name:         opencis-master
Namespace:    openshift-compliance
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"compliance.openshift.io/v1alpha1","kind":"ComplianceSuite","metadata":{"annotations":{},"name":"opencis-master","namespace"...
API Version:  compliance.openshift.io/v1alpha1
Kind:         ComplianceSuite
Metadata:
  Creation Timestamp:  2020-06-13T08:48:55Z
  Finalizers:
    suite.finalizers.compliance.openshift.io
  Generation:        2
  Resource Version:  1475787
  Self Link:         /apis/compliance.openshift.io/v1alpha1/namespaces/openshift-compliance/compliancesuites/opencis-master
  UID:               cf186b1b-bff9-44b1-b388-5eee01041709
Spec:
  Scans:
    Content:        ssg-ocp4-ds.xml
    Content Image:  quay.io/complianceascode/ocp4:latest
    Name:           master-scan
    Node Selector:
      node-role.kubernetes.io/master:
    Profile:                           xccdf_org.ssgproject.content_profile_opencis-master
    Scan Type:                         Node
  Schedule:                            0 6 * * *
Status:
  Aggregated Phase:   DONE
  Aggregated Result:  ERROR
  Scan Statuses:
    Errormsg:  No profile matching suffix "xccdf_org.ssgproject.content_profile_opencis-master" was found. Get available profiles using:
$ oscap info "/content/ssg-ocp4-ds.xml"

    Name:    master-scan
    Phase:   DONE
    Result:  ERROR
Events:
  Type    Reason           Age   From       Message
  ----    ------           ----  ----       -------
  Normal  ResultAvailable  21s   suitectrl  ComplianceSuite's result is: ERROR
```

**Comment by JAORMX** [comment]
@akilada the opencis-master profile no longer exists in the content. Try using the cis profile instead. e.g.

```
xccdf_org.ssgproject.content_profile_cis
```

We are working on enabling a more user-friendly way to browse the available content. We'll start documenting it next week.

**Comment by akilada** [comment]
@JAORMX - Thanks. The profile not found error disappeared. 

Compliance suite yaml - 

```
apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: opencis-master
spec:
  autoApplyRemediations: false
  schedule: "0 6 * * *"
  scans:
    - name: masters-scan
      scanType: Node
      profile: xccdf_org.ssgproject.content_profile_cis
      content: ssg-ocp4-ds.xml
      contentImage: quay.io/complianceascode/ocp4:latest
      nodeSelector:
        node-role.kubernetes.io/master: ""
```

I ran the CIS scan for just the masters and the result was "SKIP". Is it normal?

```
NAME                                                    STATUS   SEVERITY
masters-scan-api-server-anonymous-auth                  SKIP     medium
masters-scan-api-server-audit-log-maxage                SKIP     medium
masters-scan-api-server-audit-log-maxbackup             SKIP     low
masters-scan-api-server-audit-log-maxsize               SKIP     medium
masters-scan-api-server-audit-log-path                  SKIP     high
masters-scan-api-server-authorization-mode              SKIP     medium
masters-scan-api-server-basic-auth                      SKIP     medium
masters-scan-api-server-client-ca                       SKIP     medium
masters-scan-api-server-etcd-ca                         SKIP     medium
masters-scan-api-server-etcd-cert                       SKIP     medium
masters-scan-api-server-etcd-key                        SKIP     medium
masters-scan-api-server-insecure-bind-address           SKIP     medium
masters-scan-api-server-insecure-port                   SKIP     medium
masters-scan-api-server-kubelet-certificate-authority   SKIP     high
masters-scan-api-server-kubelet-client-cert             SKIP     high
masters-scan-api-server-kubelet-client-key              SKIP     high
masters-scan-api-server-kubelet-https                   SKIP     medium
masters-scan-api-server-request-timeout                 SKIP     medium
masters-scan-api-server-secure-port                     SKIP     medium
masters-scan-api-server-service-account-public-key      SKIP     medium
masters-scan-api-server-tls-cert                        SKIP     medium
masters-scan-api-server-tls-private-key                 SKIP     medium
masters-scan-api-server-token-auth                      SKIP     high
masters-scan-etcd-auto-tls                              SKIP     medium
masters-scan-etcd-cert-file                             SKIP     medium
masters-scan-etcd-client-cert-auth                      SKIP     medium
masters-scan-etcd-key-file                              SKIP     medium
masters-scan-etcd-peer-auto-tls                         SKIP     medium
masters-scan-etcd-peer-cert-file                        SKIP     medium
masters-scan-etcd-peer-client-cert-auth                 SKIP     medium
masters-scan-etcd-peer-key-file                         SKIP     medium
masters-scan-etcd-unique-ca                             SKIP     medium
masters-scan-etcd-wal-dir                               SKIP     medium
```
