### ISSUE TITLE
ocp4-cis scan: "warnings: the server could not find the requested resource"

### ISSUE THREAD

**Issue by darrenfoong** [openshift/compliance-operator#555]
(Follow-up to an e-mail with @JAORMX)

Setup: OpenShift 4.6.13 on AWS with Compliance Operator 0.1.24 from Operator Hub.

I created a ScanSettingBinding with the following profiles:

```
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: ocp4-cis
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: ocp4-cis-node
```

The scans finished running and I looked at the ComplianceSuite YAML.

Actual:

```
  scanStatuses:
    - name: ocp4-cis
      phase: DONE
      result: NON-COMPLIANT
      resultsStorage:
        name: ocp4-cis
        namespace: openshift-compliance
      warnings: the server could not find the requested resource # <--- interesting line
    - name: ocp4-cis-node-worker
      phase: DONE
      result: NON-COMPLIANT
      resultsStorage:
        name: ocp4-cis-node-worker
        namespace: openshift-compliance
    - name: ocp4-cis-node-master
      phase: DONE
      result: NON-COMPLIANT
      resultsStorage:
        name: ocp4-cis-node-master
        namespace: openshift-compliance
```

Expected: no warnings.
