### ISSUE TITLE
tailored profile state is Error if profile that supposed to be extended does not exist

### ISSUE THREAD

**Issue by maratsal** [openshift/compliance-operator#791]
I am using Argo CD for deployment of compliance operator and for creation of `scansettingbinding` and `tailoredprofile` resources.

When I run argo cd sync I use following annotation with sync retry option, so that sync of application will go through and argo cd will retry sync and create `scansettingbinding` and `tailoredprofile` resources when CRDs are created.
```
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```

However, if tailored profile is set to Error state, then compliance operator never tries to reconcile it and the whole setup doesn't work as scansettingbinding is waiting for tailored profile, but tailored profile is never fixed.

To fix the issue I need to delete tailored profile and scan setting binding and after that run argo cd application sync one more time.

I can play with the delay of argo cd application sync retry, but I think operator should be retrying reconciliation of the tailored profile.

Status of scansettingbinding:
```
status:
  conditions:
  - lastTransitionTime: "2022-02-07T23:27:16Z"
    message: The TailoredProfile referenced has an error and is not usable
    reason: Invalid
    status: "False"
    type: Ready
```

Status of tailored profile:
```
status:
  errorMessage: 'fetching profile to be extended: Profile.compliance.openshift.io
    "ocp4-cis" not found'
  outputRef:
    name: ""
    namespace: ""
  state: ERROR
```
